// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAlert implements createAlert operation.
//
// POST /alerts
func (UnimplementedHandler) CreateAlert(ctx context.Context, req *Alert) (r *Alert, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEvent implements createEvent operation.
//
// POST /events
func (UnimplementedHandler) CreateEvent(ctx context.Context, req *Event) (r *Event, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNotifications implements getNotifications operation.
//
// GET /notifications
func (UnimplementedHandler) GetNotifications(ctx context.Context) (r *Notification, _ error) {
	return r, ht.ErrNotImplemented
}
