// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/AdminEvent
type AdminEvent struct {
	AdminId        string    `json:"adminId"`
	Action         OptString `json:"action"`
	TargetResource OptString `json:"targetResource"`
}

// GetAdminId returns the value of AdminId.
func (s *AdminEvent) GetAdminId() string {
	return s.AdminId
}

// GetAction returns the value of Action.
func (s *AdminEvent) GetAction() OptString {
	return s.Action
}

// GetTargetResource returns the value of TargetResource.
func (s *AdminEvent) GetTargetResource() OptString {
	return s.TargetResource
}

// SetAdminId sets the value of AdminId.
func (s *AdminEvent) SetAdminId(val string) {
	s.AdminId = val
}

// SetAction sets the value of Action.
func (s *AdminEvent) SetAction(val OptString) {
	s.Action = val
}

// SetTargetResource sets the value of TargetResource.
func (s *AdminEvent) SetTargetResource(val OptString) {
	s.TargetResource = val
}

// Ref: #/components/schemas/Alert
type Alert struct {
	Severity  string    `json:"severity"`
	Message   string    `json:"message"`
	Timestamp time.Time `json:"timestamp"`
	AnyOf     AlertSum
}

// GetSeverity returns the value of Severity.
func (s *Alert) GetSeverity() string {
	return s.Severity
}

// GetMessage returns the value of Message.
func (s *Alert) GetMessage() string {
	return s.Message
}

// GetTimestamp returns the value of Timestamp.
func (s *Alert) GetTimestamp() time.Time {
	return s.Timestamp
}

// GetAnyOf returns the value of AnyOf.
func (s *Alert) GetAnyOf() AlertSum {
	return s.AnyOf
}

// SetSeverity sets the value of Severity.
func (s *Alert) SetSeverity(val string) {
	s.Severity = val
}

// SetMessage sets the value of Message.
func (s *Alert) SetMessage(val string) {
	s.Message = val
}

// SetTimestamp sets the value of Timestamp.
func (s *Alert) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// SetAnyOf sets the value of AnyOf.
func (s *Alert) SetAnyOf(val AlertSum) {
	s.AnyOf = val
}

// AlertSum represents sum type.
type AlertSum struct {
	Type             AlertSumType // switch on this field
	SecurityAlert    SecurityAlert
	PerformanceAlert PerformanceAlert
	InfoAlert        InfoAlert
}

// AlertSumType is oneOf type of AlertSum.
type AlertSumType string

// Possible values for AlertSumType.
const (
	AlertSumCritical AlertSumType = "critical"
	AlertSumHigh     AlertSumType = "high"
	AlertSumUrgent   AlertSumType = "urgent"
	AlertSumLow      AlertSumType = "low"
	AlertSumMedium   AlertSumType = "medium"
	AlertSumDebug    AlertSumType = "debug"
	AlertSumInfo     AlertSumType = "info"
)

// IsSecurityAlert reports whether AlertSum is SecurityAlert.
func (s AlertSum) IsSecurityAlert() bool {
	switch s.Type {
	case AlertSumCritical:
		return true
	case AlertSumHigh:
		return true
	case AlertSumUrgent:
		return true
	default:
		return false
	}
}

// IsPerformanceAlert reports whether AlertSum is PerformanceAlert.
func (s AlertSum) IsPerformanceAlert() bool {
	switch s.Type {
	case AlertSumLow:
		return true
	case AlertSumMedium:
		return true
	default:
		return false
	}
}

// IsInfoAlert reports whether AlertSum is InfoAlert.
func (s AlertSum) IsInfoAlert() bool {
	switch s.Type {
	case AlertSumDebug:
		return true
	case AlertSumInfo:
		return true
	default:
		return false
	}
}

// SetSecurityAlert sets AlertSum to SecurityAlert.
func (s *AlertSum) SetSecurityAlert(v SecurityAlert) {
	s.Type = AlertSumCritical
	s.SecurityAlert = v
}

// SetSecurityAlertWithType sets AlertSum to SecurityAlert with a specific discriminator value.
func (s *AlertSum) SetSecurityAlertWithType(v SecurityAlert, discriminator AlertSumType) {
	s.Type = discriminator
	s.SecurityAlert = v
}

// GetSecurityAlert returns SecurityAlert and true boolean if AlertSum is SecurityAlert.
func (s AlertSum) GetSecurityAlert() (v SecurityAlert, ok bool) {
	if !s.IsSecurityAlert() {
		return v, false
	}
	return s.SecurityAlert, true
}

// NewSecurityAlertAlertSum returns new AlertSum from SecurityAlert.
func NewSecurityAlertAlertSum(v SecurityAlert) AlertSum {
	var s AlertSum
	s.SetSecurityAlert(v)
	return s
}

// SetPerformanceAlert sets AlertSum to PerformanceAlert.
func (s *AlertSum) SetPerformanceAlert(v PerformanceAlert) {
	s.Type = AlertSumLow
	s.PerformanceAlert = v
}

// SetPerformanceAlertWithType sets AlertSum to PerformanceAlert with a specific discriminator value.
func (s *AlertSum) SetPerformanceAlertWithType(v PerformanceAlert, discriminator AlertSumType) {
	s.Type = discriminator
	s.PerformanceAlert = v
}

// GetPerformanceAlert returns PerformanceAlert and true boolean if AlertSum is PerformanceAlert.
func (s AlertSum) GetPerformanceAlert() (v PerformanceAlert, ok bool) {
	if !s.IsPerformanceAlert() {
		return v, false
	}
	return s.PerformanceAlert, true
}

// NewPerformanceAlertAlertSum returns new AlertSum from PerformanceAlert.
func NewPerformanceAlertAlertSum(v PerformanceAlert) AlertSum {
	var s AlertSum
	s.SetPerformanceAlert(v)
	return s
}

// SetInfoAlert sets AlertSum to InfoAlert.
func (s *AlertSum) SetInfoAlert(v InfoAlert) {
	s.Type = AlertSumDebug
	s.InfoAlert = v
}

// SetInfoAlertWithType sets AlertSum to InfoAlert with a specific discriminator value.
func (s *AlertSum) SetInfoAlertWithType(v InfoAlert, discriminator AlertSumType) {
	s.Type = discriminator
	s.InfoAlert = v
}

// GetInfoAlert returns InfoAlert and true boolean if AlertSum is InfoAlert.
func (s AlertSum) GetInfoAlert() (v InfoAlert, ok bool) {
	if !s.IsInfoAlert() {
		return v, false
	}
	return s.InfoAlert, true
}

// NewInfoAlertAlertSum returns new AlertSum from InfoAlert.
func NewInfoAlertAlertSum(v InfoAlert) AlertSum {
	var s AlertSum
	s.SetInfoAlert(v)
	return s
}

// Ref: #/components/schemas/EmailNotification
type EmailNotification struct {
	Recipient string    `json:"recipient"`
	Subject   OptString `json:"subject"`
	HtmlBody  OptString `json:"htmlBody"`
}

// GetRecipient returns the value of Recipient.
func (s *EmailNotification) GetRecipient() string {
	return s.Recipient
}

// GetSubject returns the value of Subject.
func (s *EmailNotification) GetSubject() OptString {
	return s.Subject
}

// GetHtmlBody returns the value of HtmlBody.
func (s *EmailNotification) GetHtmlBody() OptString {
	return s.HtmlBody
}

// SetRecipient sets the value of Recipient.
func (s *EmailNotification) SetRecipient(val string) {
	s.Recipient = val
}

// SetSubject sets the value of Subject.
func (s *EmailNotification) SetSubject(val OptString) {
	s.Subject = val
}

// SetHtmlBody sets the value of HtmlBody.
func (s *EmailNotification) SetHtmlBody(val OptString) {
	s.HtmlBody = val
}

// Ref: #/components/schemas/Event
type Event struct {
	Type      string    `json:"type"`
	Timestamp time.Time `json:"timestamp"`
	OneOf     EventSum
}

// GetType returns the value of Type.
func (s *Event) GetType() string {
	return s.Type
}

// GetTimestamp returns the value of Timestamp.
func (s *Event) GetTimestamp() time.Time {
	return s.Timestamp
}

// GetOneOf returns the value of OneOf.
func (s *Event) GetOneOf() EventSum {
	return s.OneOf
}

// SetType sets the value of Type.
func (s *Event) SetType(val string) {
	s.Type = val
}

// SetTimestamp sets the value of Timestamp.
func (s *Event) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// SetOneOf sets the value of OneOf.
func (s *Event) SetOneOf(val EventSum) {
	s.OneOf = val
}

// EventSum represents sum type.
type EventSum struct {
	Type        EventSumType // switch on this field
	UserEvent   UserEvent
	AdminEvent  AdminEvent
	SystemEvent SystemEvent
}

// EventSumType is oneOf type of EventSum.
type EventSumType string

// Possible values for EventSumType.
const (
	EventSumUserCreated       EventSumType = "user.created"
	EventSumUserRegistered    EventSumType = "user.registered"
	EventSumUserSignup        EventSumType = "user.signup"
	EventSumAdminAction       EventSumType = "admin.action"
	EventSumAdminLogin        EventSumType = "admin.login"
	EventSumSystemMaintenance EventSumType = "system.maintenance"
	EventSumSystemShutdown    EventSumType = "system.shutdown"
	EventSumSystemStartup     EventSumType = "system.startup"
)

// IsUserEvent reports whether EventSum is UserEvent.
func (s EventSum) IsUserEvent() bool {
	switch s.Type {
	case EventSumUserCreated:
		return true
	case EventSumUserRegistered:
		return true
	case EventSumUserSignup:
		return true
	default:
		return false
	}
}

// IsAdminEvent reports whether EventSum is AdminEvent.
func (s EventSum) IsAdminEvent() bool {
	switch s.Type {
	case EventSumAdminAction:
		return true
	case EventSumAdminLogin:
		return true
	default:
		return false
	}
}

// IsSystemEvent reports whether EventSum is SystemEvent.
func (s EventSum) IsSystemEvent() bool {
	switch s.Type {
	case EventSumSystemMaintenance:
		return true
	case EventSumSystemShutdown:
		return true
	case EventSumSystemStartup:
		return true
	default:
		return false
	}
}

// SetUserEvent sets EventSum to UserEvent.
func (s *EventSum) SetUserEvent(v UserEvent) {
	s.Type = EventSumUserCreated
	s.UserEvent = v
}

// SetUserEventWithType sets EventSum to UserEvent with a specific discriminator value.
func (s *EventSum) SetUserEventWithType(v UserEvent, discriminator EventSumType) {
	s.Type = discriminator
	s.UserEvent = v
}

// GetUserEvent returns UserEvent and true boolean if EventSum is UserEvent.
func (s EventSum) GetUserEvent() (v UserEvent, ok bool) {
	if !s.IsUserEvent() {
		return v, false
	}
	return s.UserEvent, true
}

// NewUserEventEventSum returns new EventSum from UserEvent.
func NewUserEventEventSum(v UserEvent) EventSum {
	var s EventSum
	s.SetUserEvent(v)
	return s
}

// SetAdminEvent sets EventSum to AdminEvent.
func (s *EventSum) SetAdminEvent(v AdminEvent) {
	s.Type = EventSumAdminAction
	s.AdminEvent = v
}

// SetAdminEventWithType sets EventSum to AdminEvent with a specific discriminator value.
func (s *EventSum) SetAdminEventWithType(v AdminEvent, discriminator EventSumType) {
	s.Type = discriminator
	s.AdminEvent = v
}

// GetAdminEvent returns AdminEvent and true boolean if EventSum is AdminEvent.
func (s EventSum) GetAdminEvent() (v AdminEvent, ok bool) {
	if !s.IsAdminEvent() {
		return v, false
	}
	return s.AdminEvent, true
}

// NewAdminEventEventSum returns new EventSum from AdminEvent.
func NewAdminEventEventSum(v AdminEvent) EventSum {
	var s EventSum
	s.SetAdminEvent(v)
	return s
}

// SetSystemEvent sets EventSum to SystemEvent.
func (s *EventSum) SetSystemEvent(v SystemEvent) {
	s.Type = EventSumSystemMaintenance
	s.SystemEvent = v
}

// SetSystemEventWithType sets EventSum to SystemEvent with a specific discriminator value.
func (s *EventSum) SetSystemEventWithType(v SystemEvent, discriminator EventSumType) {
	s.Type = discriminator
	s.SystemEvent = v
}

// GetSystemEvent returns SystemEvent and true boolean if EventSum is SystemEvent.
func (s EventSum) GetSystemEvent() (v SystemEvent, ok bool) {
	if !s.IsSystemEvent() {
		return v, false
	}
	return s.SystemEvent, true
}

// NewSystemEventEventSum returns new EventSum from SystemEvent.
func NewSystemEventEventSum(v SystemEvent) EventSum {
	var s EventSum
	s.SetSystemEvent(v)
	return s
}

// Ref: #/components/schemas/InfoAlert
type InfoAlert struct {
	Category string              `json:"category"`
	Details  OptInfoAlertDetails `json:"details"`
	Tags     []string            `json:"tags"`
}

// GetCategory returns the value of Category.
func (s *InfoAlert) GetCategory() string {
	return s.Category
}

// GetDetails returns the value of Details.
func (s *InfoAlert) GetDetails() OptInfoAlertDetails {
	return s.Details
}

// GetTags returns the value of Tags.
func (s *InfoAlert) GetTags() []string {
	return s.Tags
}

// SetCategory sets the value of Category.
func (s *InfoAlert) SetCategory(val string) {
	s.Category = val
}

// SetDetails sets the value of Details.
func (s *InfoAlert) SetDetails(val OptInfoAlertDetails) {
	s.Details = val
}

// SetTags sets the value of Tags.
func (s *InfoAlert) SetTags(val []string) {
	s.Tags = val
}

type InfoAlertDetails map[string]string

func (s *InfoAlertDetails) init() InfoAlertDetails {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/Notification
type Notification struct {
	Channel string `json:"channel"`
	Message string `json:"message"`
	OneOf   NotificationSum
}

// GetChannel returns the value of Channel.
func (s *Notification) GetChannel() string {
	return s.Channel
}

// GetMessage returns the value of Message.
func (s *Notification) GetMessage() string {
	return s.Message
}

// GetOneOf returns the value of OneOf.
func (s *Notification) GetOneOf() NotificationSum {
	return s.OneOf
}

// SetChannel sets the value of Channel.
func (s *Notification) SetChannel(val string) {
	s.Channel = val
}

// SetMessage sets the value of Message.
func (s *Notification) SetMessage(val string) {
	s.Message = val
}

// SetOneOf sets the value of OneOf.
func (s *Notification) SetOneOf(val NotificationSum) {
	s.OneOf = val
}

// NotificationSum represents sum type.
type NotificationSum struct {
	Type              NotificationSumType // switch on this field
	EmailNotification EmailNotification
	SmsNotification   SmsNotification
	PushNotification  PushNotification
}

// NotificationSumType is oneOf type of NotificationSum.
type NotificationSumType string

// Possible values for NotificationSumType.
const (
	NotificationSumEmail  NotificationSumType = "email"
	NotificationSumMail   NotificationSumType = "mail"
	NotificationSumSMS    NotificationSumType = "sms"
	NotificationSumText   NotificationSumType = "text"
	NotificationSumApp    NotificationSumType = "app"
	NotificationSumMobile NotificationSumType = "mobile"
	NotificationSumPush   NotificationSumType = "push"
)

// IsEmailNotification reports whether NotificationSum is EmailNotification.
func (s NotificationSum) IsEmailNotification() bool {
	switch s.Type {
	case NotificationSumEmail:
		return true
	case NotificationSumMail:
		return true
	default:
		return false
	}
}

// IsSmsNotification reports whether NotificationSum is SmsNotification.
func (s NotificationSum) IsSmsNotification() bool {
	switch s.Type {
	case NotificationSumSMS:
		return true
	case NotificationSumText:
		return true
	default:
		return false
	}
}

// IsPushNotification reports whether NotificationSum is PushNotification.
func (s NotificationSum) IsPushNotification() bool {
	switch s.Type {
	case NotificationSumApp:
		return true
	case NotificationSumMobile:
		return true
	case NotificationSumPush:
		return true
	default:
		return false
	}
}

// SetEmailNotification sets NotificationSum to EmailNotification.
func (s *NotificationSum) SetEmailNotification(v EmailNotification) {
	s.Type = NotificationSumEmail
	s.EmailNotification = v
}

// SetEmailNotificationWithType sets NotificationSum to EmailNotification with a specific discriminator value.
func (s *NotificationSum) SetEmailNotificationWithType(v EmailNotification, discriminator NotificationSumType) {
	s.Type = discriminator
	s.EmailNotification = v
}

// GetEmailNotification returns EmailNotification and true boolean if NotificationSum is EmailNotification.
func (s NotificationSum) GetEmailNotification() (v EmailNotification, ok bool) {
	if !s.IsEmailNotification() {
		return v, false
	}
	return s.EmailNotification, true
}

// NewEmailNotificationNotificationSum returns new NotificationSum from EmailNotification.
func NewEmailNotificationNotificationSum(v EmailNotification) NotificationSum {
	var s NotificationSum
	s.SetEmailNotification(v)
	return s
}

// SetSmsNotification sets NotificationSum to SmsNotification.
func (s *NotificationSum) SetSmsNotification(v SmsNotification) {
	s.Type = NotificationSumSMS
	s.SmsNotification = v
}

// SetSmsNotificationWithType sets NotificationSum to SmsNotification with a specific discriminator value.
func (s *NotificationSum) SetSmsNotificationWithType(v SmsNotification, discriminator NotificationSumType) {
	s.Type = discriminator
	s.SmsNotification = v
}

// GetSmsNotification returns SmsNotification and true boolean if NotificationSum is SmsNotification.
func (s NotificationSum) GetSmsNotification() (v SmsNotification, ok bool) {
	if !s.IsSmsNotification() {
		return v, false
	}
	return s.SmsNotification, true
}

// NewSmsNotificationNotificationSum returns new NotificationSum from SmsNotification.
func NewSmsNotificationNotificationSum(v SmsNotification) NotificationSum {
	var s NotificationSum
	s.SetSmsNotification(v)
	return s
}

// SetPushNotification sets NotificationSum to PushNotification.
func (s *NotificationSum) SetPushNotification(v PushNotification) {
	s.Type = NotificationSumApp
	s.PushNotification = v
}

// SetPushNotificationWithType sets NotificationSum to PushNotification with a specific discriminator value.
func (s *NotificationSum) SetPushNotificationWithType(v PushNotification, discriminator NotificationSumType) {
	s.Type = discriminator
	s.PushNotification = v
}

// GetPushNotification returns PushNotification and true boolean if NotificationSum is PushNotification.
func (s NotificationSum) GetPushNotification() (v PushNotification, ok bool) {
	if !s.IsPushNotification() {
		return v, false
	}
	return s.PushNotification, true
}

// NewPushNotificationNotificationSum returns new NotificationSum from PushNotification.
func NewPushNotificationNotificationSum(v PushNotification) NotificationSum {
	var s NotificationSum
	s.SetPushNotification(v)
	return s
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInfoAlertDetails returns new OptInfoAlertDetails with value set to v.
func NewOptInfoAlertDetails(v InfoAlertDetails) OptInfoAlertDetails {
	return OptInfoAlertDetails{
		Value: v,
		Set:   true,
	}
}

// OptInfoAlertDetails is optional InfoAlertDetails.
type OptInfoAlertDetails struct {
	Value InfoAlertDetails
	Set   bool
}

// IsSet returns true if OptInfoAlertDetails was set.
func (o OptInfoAlertDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInfoAlertDetails) Reset() {
	var v InfoAlertDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInfoAlertDetails) SetTo(v InfoAlertDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInfoAlertDetails) Get() (v InfoAlertDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInfoAlertDetails) Or(d InfoAlertDetails) InfoAlertDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSystemEventDetails returns new OptSystemEventDetails with value set to v.
func NewOptSystemEventDetails(v SystemEventDetails) OptSystemEventDetails {
	return OptSystemEventDetails{
		Value: v,
		Set:   true,
	}
}

// OptSystemEventDetails is optional SystemEventDetails.
type OptSystemEventDetails struct {
	Value SystemEventDetails
	Set   bool
}

// IsSet returns true if OptSystemEventDetails was set.
func (o OptSystemEventDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSystemEventDetails) Reset() {
	var v SystemEventDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSystemEventDetails) SetTo(v SystemEventDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSystemEventDetails) Get() (v SystemEventDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSystemEventDetails) Or(d SystemEventDetails) SystemEventDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserEventMetadata returns new OptUserEventMetadata with value set to v.
func NewOptUserEventMetadata(v UserEventMetadata) OptUserEventMetadata {
	return OptUserEventMetadata{
		Value: v,
		Set:   true,
	}
}

// OptUserEventMetadata is optional UserEventMetadata.
type OptUserEventMetadata struct {
	Value UserEventMetadata
	Set   bool
}

// IsSet returns true if OptUserEventMetadata was set.
func (o OptUserEventMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserEventMetadata) Reset() {
	var v UserEventMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserEventMetadata) SetTo(v UserEventMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserEventMetadata) Get() (v UserEventMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserEventMetadata) Or(d UserEventMetadata) UserEventMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PerformanceAlert
type PerformanceAlert struct {
	Metric       string     `json:"metric"`
	Threshold    float64    `json:"threshold"`
	CurrentValue OptFloat64 `json:"currentValue"`
	Duration     OptString  `json:"duration"`
}

// GetMetric returns the value of Metric.
func (s *PerformanceAlert) GetMetric() string {
	return s.Metric
}

// GetThreshold returns the value of Threshold.
func (s *PerformanceAlert) GetThreshold() float64 {
	return s.Threshold
}

// GetCurrentValue returns the value of CurrentValue.
func (s *PerformanceAlert) GetCurrentValue() OptFloat64 {
	return s.CurrentValue
}

// GetDuration returns the value of Duration.
func (s *PerformanceAlert) GetDuration() OptString {
	return s.Duration
}

// SetMetric sets the value of Metric.
func (s *PerformanceAlert) SetMetric(val string) {
	s.Metric = val
}

// SetThreshold sets the value of Threshold.
func (s *PerformanceAlert) SetThreshold(val float64) {
	s.Threshold = val
}

// SetCurrentValue sets the value of CurrentValue.
func (s *PerformanceAlert) SetCurrentValue(val OptFloat64) {
	s.CurrentValue = val
}

// SetDuration sets the value of Duration.
func (s *PerformanceAlert) SetDuration(val OptString) {
	s.Duration = val
}

// Ref: #/components/schemas/PushNotification
type PushNotification struct {
	DeviceToken string    `json:"deviceToken"`
	Badge       OptInt    `json:"badge"`
	Sound       OptString `json:"sound"`
}

// GetDeviceToken returns the value of DeviceToken.
func (s *PushNotification) GetDeviceToken() string {
	return s.DeviceToken
}

// GetBadge returns the value of Badge.
func (s *PushNotification) GetBadge() OptInt {
	return s.Badge
}

// GetSound returns the value of Sound.
func (s *PushNotification) GetSound() OptString {
	return s.Sound
}

// SetDeviceToken sets the value of DeviceToken.
func (s *PushNotification) SetDeviceToken(val string) {
	s.DeviceToken = val
}

// SetBadge sets the value of Badge.
func (s *PushNotification) SetBadge(val OptInt) {
	s.Badge = val
}

// SetSound sets the value of Sound.
func (s *PushNotification) SetSound(val OptString) {
	s.Sound = val
}

// Ref: #/components/schemas/SecurityAlert
type SecurityAlert struct {
	ThreatLevel     SecurityAlertThreatLevel `json:"threatLevel"`
	Source          string                   `json:"source"`
	AttackVector    OptString                `json:"attackVector"`
	AffectedSystems []string                 `json:"affectedSystems"`
}

// GetThreatLevel returns the value of ThreatLevel.
func (s *SecurityAlert) GetThreatLevel() SecurityAlertThreatLevel {
	return s.ThreatLevel
}

// GetSource returns the value of Source.
func (s *SecurityAlert) GetSource() string {
	return s.Source
}

// GetAttackVector returns the value of AttackVector.
func (s *SecurityAlert) GetAttackVector() OptString {
	return s.AttackVector
}

// GetAffectedSystems returns the value of AffectedSystems.
func (s *SecurityAlert) GetAffectedSystems() []string {
	return s.AffectedSystems
}

// SetThreatLevel sets the value of ThreatLevel.
func (s *SecurityAlert) SetThreatLevel(val SecurityAlertThreatLevel) {
	s.ThreatLevel = val
}

// SetSource sets the value of Source.
func (s *SecurityAlert) SetSource(val string) {
	s.Source = val
}

// SetAttackVector sets the value of AttackVector.
func (s *SecurityAlert) SetAttackVector(val OptString) {
	s.AttackVector = val
}

// SetAffectedSystems sets the value of AffectedSystems.
func (s *SecurityAlert) SetAffectedSystems(val []string) {
	s.AffectedSystems = val
}

type SecurityAlertThreatLevel string

const (
	SecurityAlertThreatLevelLow      SecurityAlertThreatLevel = "low"
	SecurityAlertThreatLevelMedium   SecurityAlertThreatLevel = "medium"
	SecurityAlertThreatLevelHigh     SecurityAlertThreatLevel = "high"
	SecurityAlertThreatLevelCritical SecurityAlertThreatLevel = "critical"
)

// AllValues returns all SecurityAlertThreatLevel values.
func (SecurityAlertThreatLevel) AllValues() []SecurityAlertThreatLevel {
	return []SecurityAlertThreatLevel{
		SecurityAlertThreatLevelLow,
		SecurityAlertThreatLevelMedium,
		SecurityAlertThreatLevelHigh,
		SecurityAlertThreatLevelCritical,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SecurityAlertThreatLevel) MarshalText() ([]byte, error) {
	switch s {
	case SecurityAlertThreatLevelLow:
		return []byte(s), nil
	case SecurityAlertThreatLevelMedium:
		return []byte(s), nil
	case SecurityAlertThreatLevelHigh:
		return []byte(s), nil
	case SecurityAlertThreatLevelCritical:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SecurityAlertThreatLevel) UnmarshalText(data []byte) error {
	switch SecurityAlertThreatLevel(data) {
	case SecurityAlertThreatLevelLow:
		*s = SecurityAlertThreatLevelLow
		return nil
	case SecurityAlertThreatLevelMedium:
		*s = SecurityAlertThreatLevelMedium
		return nil
	case SecurityAlertThreatLevelHigh:
		*s = SecurityAlertThreatLevelHigh
		return nil
	case SecurityAlertThreatLevelCritical:
		*s = SecurityAlertThreatLevelCritical
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SmsNotification
type SmsNotification struct {
	PhoneNumber string    `json:"phoneNumber"`
	ShortCode   OptString `json:"shortCode"`
}

// GetPhoneNumber returns the value of PhoneNumber.
func (s *SmsNotification) GetPhoneNumber() string {
	return s.PhoneNumber
}

// GetShortCode returns the value of ShortCode.
func (s *SmsNotification) GetShortCode() OptString {
	return s.ShortCode
}

// SetPhoneNumber sets the value of PhoneNumber.
func (s *SmsNotification) SetPhoneNumber(val string) {
	s.PhoneNumber = val
}

// SetShortCode sets the value of ShortCode.
func (s *SmsNotification) SetShortCode(val OptString) {
	s.ShortCode = val
}

// Ref: #/components/schemas/SystemEvent
type SystemEvent struct {
	Service string                `json:"service"`
	Version OptString             `json:"version"`
	Details OptSystemEventDetails `json:"details"`
}

// GetService returns the value of Service.
func (s *SystemEvent) GetService() string {
	return s.Service
}

// GetVersion returns the value of Version.
func (s *SystemEvent) GetVersion() OptString {
	return s.Version
}

// GetDetails returns the value of Details.
func (s *SystemEvent) GetDetails() OptSystemEventDetails {
	return s.Details
}

// SetService sets the value of Service.
func (s *SystemEvent) SetService(val string) {
	s.Service = val
}

// SetVersion sets the value of Version.
func (s *SystemEvent) SetVersion(val OptString) {
	s.Version = val
}

// SetDetails sets the value of Details.
func (s *SystemEvent) SetDetails(val OptSystemEventDetails) {
	s.Details = val
}

type SystemEventDetails map[string]jx.Raw

func (s *SystemEventDetails) init() SystemEventDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/UserEvent
type UserEvent struct {
	UserId   string               `json:"userId"`
	Email    OptString            `json:"email"`
	Metadata OptUserEventMetadata `json:"metadata"`
}

// GetUserId returns the value of UserId.
func (s *UserEvent) GetUserId() string {
	return s.UserId
}

// GetEmail returns the value of Email.
func (s *UserEvent) GetEmail() OptString {
	return s.Email
}

// GetMetadata returns the value of Metadata.
func (s *UserEvent) GetMetadata() OptUserEventMetadata {
	return s.Metadata
}

// SetUserId sets the value of UserId.
func (s *UserEvent) SetUserId(val string) {
	s.UserId = val
}

// SetEmail sets the value of Email.
func (s *UserEvent) SetEmail(val OptString) {
	s.Email = val
}

// SetMetadata sets the value of Metadata.
func (s *UserEvent) SetMetadata(val OptUserEventMetadata) {
	s.Metadata = val
}

type UserEventMetadata map[string]string

func (s *UserEventMetadata) init() UserEventMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}
