// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s *Alert) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.AnyOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "AnyOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AlertSum) Validate() error {
	switch s.Type {
	case AlertSumCritical:
		if err := s.SecurityAlert.Validate(); err != nil {
			return err
		}
		return nil
	case AlertSumHigh:
		if err := s.SecurityAlert.Validate(); err != nil {
			return err
		}
		return nil
	case AlertSumUrgent:
		if err := s.SecurityAlert.Validate(); err != nil {
			return err
		}
		return nil
	case AlertSumLow:
		if err := s.PerformanceAlert.Validate(); err != nil {
			return err
		}
		return nil
	case AlertSumMedium:
		if err := s.PerformanceAlert.Validate(); err != nil {
			return err
		}
		return nil
	case AlertSumDebug:
		return nil // no validation needed
	case AlertSumInfo:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *EmailNotification) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:    0,
			MinLengthSet: false,
			MaxLength:    0,
			MaxLengthSet: false,
			Email:        true,
			Hostname:     false,
			Regex:        nil,
		}).Validate(string(s.Recipient)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "recipient",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *Notification) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s NotificationSum) Validate() error {
	switch s.Type {
	case NotificationSumEmail:
		if err := s.EmailNotification.Validate(); err != nil {
			return err
		}
		return nil
	case NotificationSumMail:
		if err := s.EmailNotification.Validate(); err != nil {
			return err
		}
		return nil
	case NotificationSumSMS:
		return nil // no validation needed
	case NotificationSumText:
		return nil // no validation needed
	case NotificationSumApp:
		return nil // no validation needed
	case NotificationSumMobile:
		return nil // no validation needed
	case NotificationSumPush:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *PerformanceAlert) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Float{}).Validate(float64(s.Threshold)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "threshold",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CurrentValue.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "currentValue",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SecurityAlert) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.ThreatLevel.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "threatLevel",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SecurityAlertThreatLevel) Validate() error {
	switch s {
	case "low":
		return nil
	case "medium":
		return nil
	case "high":
		return nil
	case "critical":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
