// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAlertOperation      OperationName = "CreateAlert"
	CreateEventOperation      OperationName = "CreateEvent"
	GetNotificationsOperation OperationName = "GetNotifications"
)
