// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateAlert implements createAlert operation.
	//
	// POST /alerts
	CreateAlert(ctx context.Context, req *Alert) (*Alert, error)
	// CreateEvent implements createEvent operation.
	//
	// POST /events
	CreateEvent(ctx context.Context, req *Event) (*Event, error)
	// GetNotifications implements getNotifications operation.
	//
	// GET /notifications
	GetNotifications(ctx context.Context) (*Notification, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
